FROM codercom/code-server:4.96.4

USER root
RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER coder

EXPOSE 8080 3000

RUN wget https://github.com/code100x/remote-vscode-extension/raw/refs/heads/main/bolty-listener-0.0.1.vsix
RUN code-server --install-extension bolty-listener-0.0.1.vsix

# No git clone here - rely on volume mount
# RUN git clone https://github.com/code100x/base-react-native-expo.git /tmp/bolty-worker
# RUN cd /tmp/bolty-worker && npm install

CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "/tmp/bolty-worker"]
