FROM codercom/code-server:4.96.4

USER root
RUN apt-get update \
    && apt-get install -y curl gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER coder

EXPOSE 8080 3000 5173

CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "0.0.0.0:3000", "0.0.0.0:5173",   "/anon/build"]
