version: '3.8'

services:
  llm_backend:
    image: llm
    ports:
      - "3000:3000"
    volumes:
      - "C:/Users/Nikhil/OneDrive/Desktop/before hacker house/spin_up_backend/anon_files:/app/app/anon_files"
    restart: unless-stopped
    container_name: llm

  code_server:
    image: anon_new
    ports:
      - "8080:8080"
      - "5173:5173"
      - "3001:3001"
    volumes:
      - "C:/Users/Nikhil/OneDrive/Desktop/before hacker house/spin_up_backend/anon_files:/anon/build"
    privileged: true
    cap_add:
      - ALL
    user: rootcl
    restart: unless-stopped
    container_name: vs_code
