# Use Node.js as base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

# Build the TypeScript code
RUN npm run build

# Expose the port your app runs on (change if needed)
EXPOSE 3000

# Start the server from dist folder`
CMD ["node", "dist/index.js"]
